name: odev_takip
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Yardımcılar
  cupertino_icons: ^1.0.6
  intl: ^0.18.1
  
# Firebase Paketleri
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.0
  google_sign_in: ^6.2.1

  # HIVE (Veritabanı)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  fl_chart: ^0.66.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1  # Bunu ekle
  
  # Kod Üreticiler
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/at-logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true  # iOS için de otomatik yapsın
  image_path: "assets/at-logo.png"
  min_sdk_android: 21 # İsteğe bağlı
  adaptive_icon_background: "#FFFFFF" # Arka plan rengi (beyaz)
  adaptive_icon_foreground: "assets/at-logo.png"